/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoGrafo;

import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author josse
 */
public class GrafosVisual extends javax.swing.JFrame {

    /**
     * Creates new form GrafosVisual
     */
    public GrafosVisual() {
        initComponents();

    }
    Metodos m = new Metodos();
    Grafo gr = new Grafo();

    ArrayList<Integer> posx = new ArrayList<>();
    ArrayList<Integer> posy = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearCirculoClick(evt);
                CrearLineaClick(evt);
                CalcularGasto(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Crear nodos");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Unir nodos");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(651, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(646, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearCirculoClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCirculoClick
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            System.out.println("Creando nodos");

            //Obtiene la posicion del mouse al hacer click
            Point cord = MouseInfo.getPointerInfo().getLocation();
            int cord_x = cord.x;
            int cord_y = cord.y;
            System.out.println(cord_x + " " + cord_y);

            //Pregunta por el nombre del nodo
            char[] c = JOptionPane.showInputDialog(this, "Nombre del grafo:").toCharArray();
            m.ciruclo(this.getGraphics(), cord_x, cord_y, c);
            posx.add(cord_x);
            posy.add(cord_y);

        }
    }//GEN-LAST:event_CrearCirculoClick

    private void CrearLineaClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearLineaClick
        // TODO add your handling code here:
        if (jRadioButton2.isSelected()) {
            System.out.println("Creando vectores");
            int maxx, minx, maxy, miny;
            int linea1x, linea1y, linea2x, linea2y;

            //Obtiene la posicion del mouse al hacer click
            Point cord = MouseInfo.getPointerInfo().getLocation();
            int cord_x = cord.x;
            int cord_y = cord.y;

            //Crea el area del ciruclo y la compara con las areas de todos los ciruclos
            for (int i = 0; i < posx.size(); i++) {
                maxx = posx.get(i) + 25;
                minx = posx.get(i) - 25;
                maxy = posy.get(i) + 25;
                miny = posy.get(i) - 25;
                if (cord_x < maxx && cord_x > minx) {
                    if (cord_y < maxy && cord_y > miny) {
                        linea1x = cord.x;
                        linea1y = cord.y;
                        System.out.println(linea1x + " " + linea1y);
                        Point cord2 = MouseInfo.getPointerInfo().getLocation();
                        System.out.println(cord2);
                        //JOptionPane.showMessageDialog(this, "Nodo 1 seleccionado");
                        System.out.println("cordenada 1 " + cord);
                        for (int j = 0; j < posx.size(); j++) {

                        }
//                        for (int j = 0; j < posx.size(); j++) {
//                            maxx = posx.get(j) + 25;
//                            minx = posx.get(j) - 25;
//                            maxy = posy.get(j) + 25;
//                            miny = posy.get(j) - 25;
//                            if (cord_x < maxx && cord_x > minx) {
//                                if (cord_y < maxy && cord_y > miny) {
//                                    System.out.println("Nodo 2 seleccionado");
//                                    m.linea(this.getGraphics(), linea1x, linea1y, 100, 100);
//                                }
//                            }
//                        }
                    }
                }
            }
    }//GEN-LAST:event_CrearLineaClick
    }
    private void CalcularGasto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcularGasto
        // TODO add your handling code here:
        if (jRadioButton3.isSelected()) {

        }
    }//GEN-LAST:event_CalcularGasto

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrafosVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrafosVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrafosVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrafosVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrafosVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
